### ISSUE TITLE
ValueErrors

### ISSUE THREAD

**Issue by packetcat** [larryng/narwal#1]
> > > import narwal
> > > session = narwal.Reddit(user_agent='hellonarwal')
> > > page1 = session.hot()
> > > print page1[0]

With that I get, this traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/narwal/things.py", line 77, in **str**
    return self.**unicode**().encode('utf-8', 'replace')
  File "/usr/local/lib/python2.6/dist-packages/narwal/things.py", line 329, in **unicode**
    return u'({}) {}'.format(self.score, self.title)
ValueError: zero length field name in format

**Comment by packetcat** [comment]
Hmm, this might be an issue with Python 2.6
"Python 2.6 must have positional arguments for format."

**Comment by packetcat** [comment]
Pull request for issue added.
